import React from "react";
import Head from "next/head";

export default function header() {
  return (
    <header>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
    </header>
  );
}
